spring.application.name=botanix
spring.datasource.url=jdbc:mysql://localhost:3306/botanix
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hipernate.ddl-auto=update
spring.jpa.show-sql=true

